model: GradientBoostingRegressor

evaluation_metric: mae

static_parameters:
  random_state: 42
  #loss: quantile
  #alpha: 0.5
  n_iter_no_change: null
  validation_fraction: null

cv_optmize_sample: 10000

parametric_space:
  learning_rate: Real(0.02,1,prior='log-uniform', transform = 'identity')
  n_estimators: Integer(80,1000, prior='log-uniform')
  #criterion: Categorical(['squared_error', 'friedman_mse'])
  min_samples_split: Integer(2,6)
  max_depth: Integer(4,20)
  #max_features: Categorical(['auto', 'sqrt', 'log2'])

hyperparameter_tunning:
  strategy: BayesSearchCV #RandomizedSearch # BayesSearchCV
  random_samples: 1000
  n_iter: 100
  scoring: neg_mean_squared_error # (customized_score, neg_mean_squared_error)
  cv: 5
  verbose: 1

parametric_space_path: models/GradientBoostingRegressor/config.json
