logs_directory_path: logs/
interim_directory_path: data/interim/
processed_directory_path: data/processed/
predicted_directory_path: data/predicted/
raw_data_relational_scrapped: data/raw/relational_scrapped/
model_artifacts_path: models/
data_external_neighbor_path: data/external/neighbor_regions_pc.csv
data_external_region_pop_path: data/external/ibge_populacao_bairro.csv
data_external_region_min_income_pct_path: data/external/ibge_porc_domicilio_salario_min.csv
data_external_region_avg_income_path: data/external/ibge_renda_media.csv
data_external_region_literacy_path: data/external/ibge_taxa_alfabetizacao_bairro.csv
